# Generated by Django 6.0.6 on 2026-07-08 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('theme', models.CharField(blank=True, max_length=255)),
                ('daily_budget_food', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_budget_transport', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_budget_activities', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('daily_budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Daily itineraries',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], max_length=20)),
                ('time', models.CharField(blank=True, max_length=10)),
                ('restaurant', models.CharField(blank=True, max_length=255)),
                ('osm_query', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('recommended_orders', models.JSONField(blank=True, default=list)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('daily_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to='api.dailyitinerary')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='ToGoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('arrival_time', models.CharField(blank=True, max_length=10)),
                ('departure_time', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('osm_query', models.CharField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('crowd_level_notes', models.TextField(blank=True)),
                ('accessibility', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geocoded', models.BooleanField(default=False)),
                ('transport', models.JSONField(blank=True, default=dict)),
                ('daily_itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_go_locations', to='api.dailyitinerary')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('days', models.PositiveIntegerField()),
                ('nights', models.PositiveIntegerField()),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('travelers', models.PositiveIntegerField(default=1)),
                ('vibe_mood', models.CharField(blank=True, max_length=255)),
                ('vibe_description', models.TextField(blank=True)),
                ('vibe_color_palette', models.JSONField(blank=True, default=list)),
                ('vibe_photo_style_notes', models.TextField(blank=True)),
                ('group_considerations', models.TextField(blank=True)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('budget_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_recommended', models.BooleanField(default=True)),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('hotel_osm_query', models.CharField(blank=True, max_length=500)),
                ('hotel_address', models.CharField(blank=True, max_length=500)),
                ('hotel_type', models.CharField(blank=True, max_length=100)),
                ('hotel_estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hotel_accessibility', models.TextField(blank=True)),
                ('hotel_latitude', models.FloatField(blank=True, null=True)),
                ('hotel_longitude', models.FloatField(blank=True, null=True)),
                ('hotel_geocoded', models.BooleanField(default=False)),
                ('transportation_type', models.CharField(blank=True, max_length=255)),
                ('transportation_recommended', models.BooleanField(default=True)),
                ('transportation_estimated_carbon_kg_co2', models.FloatField(blank=True, null=True)),
                ('transportation_carbon_comparison_notes', models.TextField(blank=True)),
                ('travel_tips', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyitinerary',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_itinerary', to='api.trip'),
        ),
        migrations.CreateModel(
            name='BudgetBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('food', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activities', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shopping', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('misc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_breakdown', to='api.trip')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dailyitinerary',
            unique_together={('trip', 'day')},
        ),
    ]
