export function generatedResultToTripPayload(result) {
  const trip = result?.trip || {}

  return {
    destination: trip.destination,
    country: trip.country,
    days: trip.days,
    nights: trip.nights,
    currency: trip.currency,
    travelers: trip.travelers,
    vibe_mood: trip.vibe?.mood || '',
    vibe_description: trip.vibe?.description || '',
    vibe_color_palette: trip.vibe?.color_palette || [],
    vibe_photo_style_notes: trip.vibe?.photo_style_notes || '',
    group_considerations: trip.group_considerations || '',
    accessibility_notes: trip.accessibility_notes || '',
    budget_total: trip.budget?.total || 0,
    budget_recommended: trip.budget?.recommended ?? true,
    hotel_name: trip.hotel?.name || '',
    hotel_osm_query: trip.hotel?.osm_query || '',
    hotel_address: trip.hotel?.address || '',
    hotel_type: trip.hotel?.type || '',
    hotel_estimated_cost: trip.hotel?.estimated_cost || 0,
    hotel_accessibility: trip.hotel?.accessibility || '',
    hotel_latitude: trip.hotel?.latitude ?? null,
    hotel_longitude: trip.hotel?.longitude ?? null,
    hotel_geocoded: trip.hotel?.geocoded ?? false,
    transportation_type: trip.transportation?.type || '',
    transportation_recommended: trip.transportation?.recommended ?? true,
    transportation_estimated_carbon_kg_co2: trip.transportation?.estimated_carbon_kg_co2 ?? null,
    transportation_carbon_comparison_notes: trip.transportation?.carbon_comparison_notes || '',
    travel_tips: result?.travel_tips || [],
    budget_breakdown: result?.budget_breakdown,
    daily_itinerary: (result?.daily_itinerary || []).map((day) => ({
      day: day.day,
      theme: day.theme,
      daily_budget_food: day.daily_budget?.food || 0,
      daily_budget_transport: day.daily_budget?.transport || 0,
      daily_budget_activities: day.daily_budget?.activities || 0,
      daily_budget_total: day.daily_budget?.total || 0,
      meal_plan: (day.meal_plan || []).map((meal) => ({
        type: meal.type,
        time: meal.time,
        restaurant: meal.restaurant,
        osm_query: meal.osm_query,
        address: meal.address,
        recommended_orders: meal.recommended_orders || [],
        estimated_cost: meal.estimated_cost || 0,
        latitude: meal.latitude ?? null,
        longitude: meal.longitude ?? null,
      })),
      to_go_locations: (day.to_go_locations || []).map((location) => ({
        order: location.order,
        arrival_time: location.arrival_time,
        departure_time: location.departure_time,
        name: location.name,
        osm_query: location.osm_query,
        address: location.address,
        description: location.description,
        estimated_cost: location.estimated_cost || 0,
        estimated_duration_minutes: location.estimated_duration_minutes ?? null,
        crowd_level_notes: location.crowd_level_notes || '',
        accessibility: location.accessibility || '',
        latitude: location.latitude ?? null,
        longitude: location.longitude ?? null,
        geocoded: location.geocoded ?? false,
        transport: location.transport || {},
      })),
    })),
  }
}

export function savedTripToResult(trip) {
  return {
    id: trip.id,
    trip: {
      destination: trip.destination,
      country: trip.country,
      days: trip.days,
      nights: trip.nights,
      currency: trip.currency,
      travelers: trip.travelers,
      vibe: {
        mood: trip.vibe_mood,
        description: trip.vibe_description,
        color_palette: trip.vibe_color_palette || [],
        photo_style_notes: trip.vibe_photo_style_notes,
      },
      group_considerations: trip.group_considerations,
      accessibility_notes: trip.accessibility_notes,
      budget: {
        total: trip.budget_total,
        recommended: trip.budget_recommended,
      },
      hotel: {
        name: trip.hotel_name,
        osm_query: trip.hotel_osm_query,
        address: trip.hotel_address,
        type: trip.hotel_type,
        estimated_cost: trip.hotel_estimated_cost,
        accessibility: trip.hotel_accessibility,
        latitude: trip.hotel_latitude,
        longitude: trip.hotel_longitude,
        geocoded: trip.hotel_geocoded,
      },
      transportation: {
        type: trip.transportation_type,
        recommended: trip.transportation_recommended,
        estimated_carbon_kg_co2: trip.transportation_estimated_carbon_kg_co2,
        carbon_comparison_notes: trip.transportation_carbon_comparison_notes,
      },
    },
    daily_itinerary: (trip.daily_itinerary || []).map((day) => ({
      day: day.day,
      theme: day.theme,
      meal_plan: day.meal_plan || [],
      to_go_locations: day.to_go_locations || [],
      daily_budget: {
        food: day.daily_budget_food,
        transport: day.daily_budget_transport,
        activities: day.daily_budget_activities,
        total: day.daily_budget_total,
      },
    })),
    budget_breakdown: trip.budget_breakdown,
    travel_tips: trip.travel_tips || [],
  }
}
